# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

iNMF_BCD <- function(count_list, Label, K_l, K, lda1, lda2, eps = 1e-5, thre_niter = 5000L, thre_delta = 0.00001, seed = 1L, loop = TRUE) {
    .Call('_scINSIGHT_iNMF_BCD', PACKAGE = 'scINSIGHT', count_list, Label, K_l, K, lda1, lda2, eps, thre_niter, thre_delta, seed, loop)
}

iNMF_BCD_Decrease <- function(count_list, Label, K_l, K, lda1, lda2, eps = 1e-5, thre_niter = 5000L, thre_delta = 0.00001, seed = 1L, loop = TRUE) {
    .Call('_scINSIGHT_iNMF_BCD_Decrease', PACKAGE = 'scINSIGHT', count_list, Label, K_l, K, lda1, lda2, eps, thre_niter, thre_delta, seed, loop)
}

iNMF_BCD_Increase <- function(count_list, Label, K_l, K, lda1, lda2, eps = 1e-5, thre_niter = 5000L, thre_delta = 0.00001, seed = 1L, loop = TRUE) {
    .Call('_scINSIGHT_iNMF_BCD_Increase', PACKAGE = 'scINSIGHT', count_list, Label, K_l, K, lda1, lda2, eps, thre_niter, thre_delta, seed, loop)
}

